image: jguyomard/hugo-builder:0.49-extras

stages:
- build
- deploy

variables:
  BUILD_DIR: $CI_PROJECT_DIR/build
  SITES_BUCKET: gs://sites.monax.io

# Job templates
.build_site: &build_template
  stage: build
  before_script:
    - apk add --update --no-cache bash curl jq
  script:
    - scripts/pricing_getter.sh
    - |
      hugo \
        --baseURL="https://$SITE_NAME/" \
        --destination=$BUILD_DIR \
        --verbose=true \
        --buildDrafts=false \
        --buildExpired=false \
        --buildFuture=false \
        --cleanDestinationDir=true \
        --forceSyncStatic=true \
        --gc=true
    - |
      minify \
        --verbose \
        --html-keep-default-attrvals \
        --html-keep-document-tags \
        --html-keep-end-tags \
        --recursive \
        --output=$BUILD_DIR/ \
        $BUILD_DIR/

.save_artifacts_template: &save_artifacts_template
  artifacts:
    paths:
      - build

.deploy_template: &deploy_template
  stage: deploy
  image: quay.io/monax/build:latest
  before_script:
    - |
      echo $GCS_CLIENT_SECRET_SITES > client-secret.json
      gcloud auth activate-service-account --key-file client-secret.json
      rm client-secret.json && unset GCS_CLIENT_SECRET_SITES
  script:
    - gsutil -m rsync -r -d $BUILD_DIR $SITES_BUCKET/$SITE_NAME

# Variable packages
.variables_staging: &vars_staging
  only:
    - staging@revenue/monax.io
  variables:
    SITE_NAME: "staging.monax.io"

.variables_production: &vars_production
  only:
    - production@revenue/monax.io
  variables:
    SITE_NAME: "monax.io"

# Build jobs
build generic:
  except:
    - staging@revenue/monax.io
    - production@revenue/monax.io
  variables:
    SITE_NAME: "test.monax.io"
  <<: *build_template

build staging:
  <<: *vars_staging
  <<: *build_template
  <<: *save_artifacts_template

build production:
  <<: *vars_production
  <<: *build_template
  <<: *save_artifacts_template

# Deploy jobs
deploy staging:
  environment:
    name: staging
    url: https://staging.monax.io
  dependencies:
    - build staging
  <<: *vars_staging
  <<: *deploy_template

deploy production:
  environment:
    name: production
    url: https://monax.io
  dependencies:
    - build production
  <<: *vars_production
  <<: *deploy_template
