image: jguyomard/hugo-builder:0.42-extras

stages:
# - cache
- build
- deploy

# cache site:
#   stage: cache
#   image: quay.io/monax/build:latest
#   only:
#     - staging@success/monax.io
#     - production@success/monax.io
#   # before_script:
#   #   - apk --no-cache --update add autoconf automake libpng-dev g++ make zlib-dev nasm
#   #   - npm install -g bower
#   script:
#     - npm install
#     # - bower install --allow-root
#   cache:
#     key: $CI_COMMIT_REF_NAME
#     paths:
#       - $CI_PROJECT_DIR/node_modules/
#       # - $CI_PROJECT_DIR/bower_components
#       # - $CI_PROJECT_DIR/source/assets/
#   artifacts:
#     paths:
#       - $CI_PROJECT_DIR/node_modules/
#       # - $CI_PROJECT_DIR/bower_components
#       # - $CI_PROJECT_DIR/source/assets/

  # Job templates
.build_site: &build_template
  stage: build
  # dependencies:
  #   - cache site
  before_script:
    # - apk --no-cache --update add nodejs
    # - npm install -g gulp
  script:
    # - gulp build
    - |
      hugo \
        --destination build \
        --verbose \
        --baseURL="https://$SITE_NAME/"
  artifacts:
    paths:
      - build

.deploy_template: &deploy_template
  stage: deploy
  image: quay.io/monax/build:latest
  before_script:
    - |
      echo $GCS_CLIENT_SECRET_SITES > client-secret.json
      gcloud auth activate-service-account --key-file client-secret.json
      rm client-secret.json
  script:
    - gsutil -m rsync -r -d build gs://sites.monax.io/$SITE_NAME

# Variable packages
.variables_staging: &vars_staging
  only:
    - staging@success/monax.io
  variables:
    SITE_NAME: "staging.monax.io"

.variables_production: &vars_production
  only:
    - production@success/monax.io
  variables:
    SITE_NAME: "monax.io"

# Build jobs
build staging:
  <<: *vars_staging
  <<: *build_template

build production:
  <<: *vars_production
  <<: *build_template

# Deploy jobs
deploy staging:
  environment:
    name: staging
    url: https://staging.monax.io
  dependencies:
    - build staging
  <<: *vars_staging
  <<: *deploy_template

deploy production:
  environment:
    name: production
    url: https://monax.io
  dependencies:
    - build production
  <<: *vars_production
  <<: *deploy_template
