# ----------------------- #
#      Main Configs       #
# ----------------------- #

name:        Eris Industries
# url:         https://erisindustries.com
# url:         https://readying.erisindustries.com
url:         http://localhost:4000
formal_name: "Eris Industries, Ltd."
description: "We empower developers to embrace participatory software architecture via distributed computing and smart contract systems."
keywords:    "blockchain,dapp,dao,dac,distributed,computing,participatory,architecture"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

markdown:    kramdown
safe:        true
titlecase:   true
lsi:         false
highlighter: pygments
permalink:   pretty
destination: "_site/htdocs"

exclude: [".gitignore", ".ruby-version", ".ruby-gemset", "README.md", "Rakefile", "_drafts", "old-text"]

# ----------------------- #
#       Locations         #
# ----------------------- #

images_dir:  "/assets/images"
scripts_dir: "/assets/scripts"
styles_dir:  "/assets/styles"
sharing_img: "/logos/ei-logo-sharing-square.png"

# ----------------------- #
#       Analytics         #
# ----------------------- #

analytics :
  provider : getclicky
  getclicky :
    site_id : 100753928