# ----------------------- #
#      Main Configs       #
# ----------------------- #
name:        Eris Industries
url:         https://erisindustries.com
formal_name: "Eris Industries"
description: "We empower developers to embrace participatory software architecture via distributed computing and smart contract systems."
