# ----------------------- #
#      Main Configs       #
# ----------------------- #
baseurl: "http://localhost"
# baseurl: "https://monax.industries"
title: "Monax Industries"
languageCode: "en-us"

# ----------------------- #
#          Hugo           #
# ----------------------- #
archetypedir: "archetype"
contentdir: "content"
dataDir: "data"
layoutdir: "layouts"
publishdir: "public"
staticdir: "static"
themesdir: "themes"
ignoreFiles:
  - "\\.foo$"
  - "\\.boo$"
  - "content/blog/images/*"
  - "content/blog/drafts/*"

theme: ""
metadataformat: "yaml"
defaultExtension: "html"

builddrafts: false
buildFuture: false
canonifyurls: true
disable404: false
disableRSS: false
disablePathToLower: false
disableSitemap: false
enableRobotsTXT: true
enableEmoji: false
noTimes: true
pygmentsCodeFences: false
pygmentsCodeFencesGuessSyntax: false
uglyURLs: false

paginate: 10
paginatePath: "page"
footnotereturnlinkcontents: "↩"
disqusShortname: erisindustriesblog

sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml

# ----------------------- #
#        Markdown         #
# ----------------------- #
blackfriday:
  # style
  smartypants: true
  angledQuotes: false
  fractions: false
  smartDashes: true
  latexDashes: true

  # html stuff
  hrefTargetBlank: true
  plainIDAnchors: true
  sourceRelativeLinksEval: true

  # extensions to use -> https://github.com/russross/blackfriday/blob/master/markdown.go
  extensions:
    - noIntraEmphasis
    - tables
    - autolink
    - strikethrough
    - footnotes
    - noEmptyLineBeforeBlock
    - headerIds
    - titleblock
    - autoHeaderIds
    - definitionLists
    - fencedCode

  # extensions not to use -> https://github.com/russross/blackfriday/blob/master/markdown.go
  extensionsmask:
    - laxHtmlBlocks
    - spaceHeaders
    - tabSizeEight
    - hardLineBreak
    - backslashLineBreak

# ----------------------- #
#        Variables        #
# ----------------------- #
permalinks:
  blog: /blog/:year/:month/:day/:title/

taxonomies:
  category: categories
  tag: tags
  topic: topics

params:
  description: "We empower developers to automate their data driven relationships."
  keywords: "blockchain,smart,contracts,data,driven,relationship,bft"
  clicky:    100753928
  mainIcon:  ei-logo-long-mobile.png
  home_buttons:
    -
      title: docs
      url: /documentation
      icon: lightbulb-o
    -
      title: code
      url: https://github.com/eris-ltd
      icon: github
    -
      title: discuss
      url: https://slack.eris.industries
      icon: slack
    -
      title: contact
      url: mailto:contact@erisindustries.com
      icon: envelope

# ----------------------- #
#          Menu           #
# ----------------------- #
menu:
  main:
    # -
    #   name: "platform"
    #   pre: "<i class='fa fa-download'></i>"
    #   url: "/platform/overview/"
    #   weight: -200
    -
      name: "products"
      pre: "<i class='fa fa-cubes'></i>"
      url: "/products/overview/"
      weight: -180
    -
      name: "legal engineering"
      pre: "<i class='fa fa-cubes'></i>"
      url: "/legal_engineering/dual_integration/"
      weight: -160
    -
      name: "team"
      pre: "<i class='fa fa-cubes'></i>"
      url: "/about/team"
      weight: -120
    -
      name: "positions"
      pre: "<i class='fa fa-cubes'></i>"
      url: "/about/positions"
      weight: -100
    -
      name: "documentation"
      pre: "<i class='fa fa-cubes'></i>"
      url: "/documentation"
      weight: -80
    -
      name: "blog"
      pre: "<i class='fa fa-cubes'></i>"
      url: "/blog/"
      weight: -60