baseurl = "https://monax.io"
title = "MONAX"
theme = "hugo-universal-theme"
themesDir = "./themes/"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# Define the number of posts per page
paginate = 6

[menu]

# Main menu


[[menu.left]]
    name = "Features"
    url  = "/features/"
    weight = 2

[[menu.left]]
    name = "Monax For"
    identifier = "monaxfor"
    url  = "#"
    weight = 3

    # sub menu items
    [[menu.left]]
      Name = "Fleet leasing"
      parent = "monaxfor"
      URL = "/for/fleet-leasing/"
      Post = "How Monax can power your fleet leases, simplify your business processes and drive new revenue streams"
      Weight = 1

    [[menu.left]]
      Name = "Corporate Governance"
      parent = "monaxfor"
      URL = "/for/corporate-governance/"
      Post = "How Monax can simplify and speed up your corporate governance, and give you full control over your agreements"
      Weight = 2

    [[menu.left]]
      Name = "Content Creators"
      parent = "monaxfor"
      URL = "/for/content-creators/"
      Post = "How Monax can strengthen your brand, protect your IP and drive new revenue streams for your content"
      Weight = 3

    [[menu.left]]
      Name = "Lawyers"
      parent = "monaxfor"
      URL = "/for/lawyers/"
      Post = "How Monax can simplify your workflow and turn your knowledge into commoditisable legal products"
      Weight = 4

[[menu.left]]
    name = "Resources"
    identifier = "resources"
    url  = "#"
    weight = 4

    # sub menu items
    [[menu.left]]
      Name = "Blog"
      parent = "resources"
      URL = "/blog/"
      Post = "Discover our journey, how we think and the paradigm shift we see happening toward legal products."
      Weight = 1

    [[menu.left]]
      Name = "Case Studies"
      parent = "resources"
      URL = "/casestudies/"
      Post = "Explore how other individuals and companies are transforming business with Monax"
      Weight = 2

    [[menu.left]]
      Name = "Explainers"
      parent = "resources"
      URL = "/explainers/"
      Post = "Learn how Monax can help you streamline your business. Explore best practices for Monax tools and ask questions."
      Weight = 3

    # [[menu.left]]
    #   Name = "Company News"
    #   parent = "resources"
    #   URL = "/news/"
    #   Post = "Keep up to date on all things Monax"
    #   Weight = 4

    [[menu.left]]
      Name = "Webinars"
      parent = "resources"
      URL = "/webinars/"
      Post = "Join us for industry insight and best practice advice on using legal products to streamline your business."
      Weight = 5

[[menu.left]]
    name = "Company"
    url  = "/company/"
    weight = 5

[[menu.register]]
    name = "Try For Free"
    url  = "#"
    weight = 1

[[menu.login]]
    name = "Login"
    url  = "#"
    weight = 7


# Top bar social links menu [UNUSED]

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/monax"
    pre = "<i class='fa fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "https://www.facebook.com/monaxHQ/"
    pre = "<i class='fa fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "https://twitter.com/monaxhq"
    pre = "<i class='fa fa-2x fa-twitter'></i>"

#! set email
[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:contact@monax.io"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/archive/"
    author = "Monax"
    defaultKeywords = ["monax", "agreements network"]
    defaultDescription = "Monax"

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "green"

    # Import fonts
    googlefonts = ["Montserrat:200,300,400,600", "Source Code Pro", "Caveat"]
    fontbody = 'Montserrat'
    fontheadings = 'Montserrat'
    fontcode = 'Source Code Pro'

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "info@monax.io"

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "/img/logo.png"

[Permalinks]
    blog = "/blog/:year/:month/:title/"
    casestudies = "/casestudies/:title/"
    explainers = "/explainers/:title/"
    news = "/news/:year/:month/:title/"
    webinars = "/webinars/:year/:month/:title/"
    for = "/for/:title"


# Enable or disable top bar with social icons
[params.topbar]
    enable = false

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.recent_posts]
    enable = false
    title = "From our blog"
    subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
