# ----------------------- #
#      Main Configs       #
# ----------------------- #
baseurl: "http://localhost/"
# baseurl: "https://monax.io/"
title: "Monax"
languageCode: "en-us"

# ----------------------- #
#          Hugo           #
# ----------------------- #
archetypedir: "archetype"
contentdir: "content"
dataDir: "data"
layoutdir: "layouts"
publishdir: "build"
staticdir: "static"
ignoreFiles:
  - "content/blog/images/*"
  - "content/blog/drafts/*"

theme: ""
metadataformat: "yaml"
defaultExtension: "html"

builddrafts: false
buildFuture: false
canonifyurls: true
disablePathToLower: false
enableRobotsTXT: true
enableEmoji: false
noTimes: true
pygmentsCodeFences: false
pygmentsCodeFencesGuessSyntax: false
uglyURLs: false

paginate: 10
paginatePath: "page"
footnotereturnlinkcontents: "↩"
# disqusShortname: erisindustriesblog

sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml

# ----------------------- #
#        Markdown         #
# ----------------------- #
blackfriday:
  # style
  smartypants: true
  angledQuotes: false
  fractions: false
  smartDashes: true
  latexDashes: true

  # html stuff
  hrefTargetBlank: true
  plainIDAnchors: true
  sourceRelativeLinksEval: false

  # extensions to use -> https://github.com/russross/blackfriday/blob/master/markdown.go
  extensions:
    - noIntraEmphasis
    - tables
    - autolink
    - strikethrough
    - footnotes
    - noEmptyLineBeforeBlock
    - headerIds
    - titleblock
    - autoHeaderIds
    - definitionLists
    - fencedCode

  # extensions not to use -> https://github.com/russross/blackfriday/blob/master/markdown.go
  extensionsmask:
    - laxHtmlBlocks
    - spaceHeaders
    - tabSizeEight
    - hardLineBreak
    - backslashLineBreak

# ----------------------- #
#        Variables        #
# ----------------------- #
permalinks:
  blog: /blog/:year/:month/:day/:title/

taxonomies:
  category: categories
  tag: tags
  author: authors
  topic: topics

params:
  keywords: "blockchain,smart,contracts,bft,ecosystem,applications,platform,active,agreements"
