baseurl = "https://monax.io"
title = "MONAX"
theme = "hugo-universal-theme"
themesDir = "./themes/"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# Define the number of posts per page
paginate = 10

[menu]

# Main menu


[[menu.left]]
    name = "Features"
    url  = "/features/"
    weight = 2

[[menu.left]]
    name = "Use Cases"
    url  = "/use-cases/"
    weight = 3

[[menu.left]]
    name = "Resources"
    url  = "/resources/"
    weight = 4

[[menu.left]]
    name = "Company"
    url  = "/company/"
    weight = 5

[[menu.left]]
    name = "*Invest"
    url  = "/investors/"
    weight = 6

[[menu.left]]
    name = "*Press"
    url  = "/press/"
    weight = 7

[[menu.register]]
    name = "Try For Free"
    url  = "#"
    weight = 1

[[menu.login]]
    name = "Login"
    url  = "#"
    weight = 7



# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/monax"
    pre = "<i class='fa fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "https://www.facebook.com/monaxHQ/"
    pre = "<i class='fa fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "https://twitter.com/monaxhq"
    pre = "<i class='fa fa-2x fa-twitter'></i>"

#! set email
[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:contact@monax.io"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "Monax"
    defaultKeywords = ["monax", "agreements network"]
    defaultDescription = "Monax"

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "green"

    # Import fonts
    googlefonts = ["Montserrat:200,300,400,600", "Source Code Pro"]
    fontbody = 'Montserrat'
    fontheadings = 'Montserrat'
    fontcode = 'Source Code Pro'

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "info@monax.io"

    about_us = "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>"
    copyright = "&copy; Monax Industries. All rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "/img/logo.png"
    address = """<p><strong>Monax Industries</strong>
        <br>123 New Avenue
        <br>Washington DC
        <br>United States
      </p>
      """

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = false
    text = ""

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.recent_posts]
    enable = false
    title = "From our blog"
    subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
