# ----------------------- #
#      Main Configs       #
# ----------------------- #
baseurl: "http://localhost"
# baseurl: "https://monax.industries"
title: "Monax Industries"
languageCode: "en-us"

# ----------------------- #
#          Hugo           #
# ----------------------- #
archetypedir: "archetype"
contentdir: "content"
dataDir: "data"
layoutdir: "layouts"
publishdir: "public"
staticdir: "static"
themesdir: "themes"
ignoreFiles:
  - "\\.foo$"
  - "\\.boo$"
  - "README.md"
  - "drafts"
  - "vendor"

theme: ""
metadataformat: "yaml"
defaultExtension: "html"

builddrafts: false
buildFuture: false
canonifyurls: true
disable404: false
disableRSS: false
disablePathToLower: false
disableSitemap: false
enableRobotsTXT: true
enableEmoji: false
noTimes: true
pygmentsCodeFences: true
pygmentsCodeFencesGuessSyntax: false
pygmentsUseClasses: true
uglyURLs: false

paginate: 10
paginatePath: "page"
footnotereturnlinkcontents: "↩"
disqusShortname: erisindustriesblog

sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml

# ----------------------- #
#        Markdown         #
# ----------------------- #
blackfriday:
  # style
  smartypants: true
  angledQuotes: false
  fractions: false
  smartDashes: true
  latexDashes: true

  # html stuff
  hrefTargetBlank: true
  plainIDAnchors: true
  sourceRelativeLinksEval: true

  # extensions to use -> https://github.com/russross/blackfriday/blob/master/markdown.go
  extensions:
    - noIntraEmphasis
    - tables
    - fencedCode
    - autolink
    - strikethrough
    - footnotes
    - noEmptyLineBeforeBlock
    - headerIds
    - titleblock
    - autoHeaderIds
    - definitionLists

  # extensions not to use -> https://github.com/russross/blackfriday/blob/master/markdown.go
  extensionsmask:
    - laxHtmlBlocks
    - spaceHeaders
    - tabSizeEight
    - hardLineBreak
    - backslashLineBreak

# ----------------------- #
#        Variables        #
# ----------------------- #
permalinks:
  blog: /blog/:year/:month/:day/:title/

taxonomies:
  category: categories
  tag: tags
  topic: topics

params:
  description: "We empower developers to automate their data driven relationships."
  keywords: "blockchain,smart,contracts,data,driven,relationship,bft"
  author:
    name:    Monax Industries
    email:   contact@monax.industries
    site:    https://monax.industries
    github:  eris-ltd
    twitter: eris_ltd
  clicky:    100753928

# ----------------------- #
#       Assets            #
# ----------------------- #

assets:
  autowrite: true
  cache: false
  prefix: "/assets"
  gzip: [ text/css, application/javascript ]

  compress:
    js: true
    css: true

  sources:
    - _assets/fonts
    - _assets/icons
    - _assets/images
    - _assets/scripts
    - _assets/styles
    - images

  features:
    automatic_img_size: false
    automatic_img_alt : false
