baseurl = "https://monax.io"
title = "Monax"
theme = "hugo-universal-theme"
site_about = "Monax is a platform to build, distribute, and operate active agreements for growing businesses."
themesDir = "./themes/"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# Define the number of posts per page
paginate = 12
rssLimit = 20

[imaging]
# Default resample filter used for resizing. Default is Box,
# a simple and fast averaging filter appropriate for downscaling.
# See https://github.com/disintegration/imaging
resampleFilter = "box"

# Defatult JPEG quality setting. Default is 75.
quality = 80

[menu]
# Main menu
[[menu.main]]
    name = "Platform"
    url  = "/platform/"
    weight = 2

[[menu.main]]
    name = "Customers"
    identifier = "customers"
    url  = "#"
    weight = 3

    # sub menu items
    # [[menu.main]]
    #   Name = "Fleet leasing"
    #   parent = "customers"
    #   URL = "/fleet-leasing/"
    #   Post = "How Monax can power your fleet leases, simplify your business processes and drive new revenue streams"
    #   Weight = 1

    [[menu.main]]
      Name = "Entrepreneurs"
      parent = "customers"
      URL = "/entrepreneurs/"
      Post = "How Monax can simplify and speed up your corporate governance, and give you full control over your agreements"
      Weight = 2

    #[[menu.main]]
    #  Name = "Creatives"
    #  parent = "customers"
    #  URL = "/creatives/"
    # Post = "How Monax can strengthen your brand, protect your IP and drive new revenue streams for your content"
    #  Weight = 3

[[menu.main]]
    Name = "Lawyers"
    indentifier = "lawyers"
    URL = "/lawyers/"
    Post = "How Monax can simplify your workflow and turn your knowledge into commoditisable legal products"
    Weight = 4

[[menu.main]]
    name = "Resources"
    identifier = "resources"
    url  = "#"
    weight = 4

    # sub menu items
    [[menu.main]]
      Name = "Blog"
      parent = "resources"
      URL = "/blog/"
      Post = "Discover our journey, how we think and the paradigm shift we see happening toward legal products."
      Weight = 1

    # [[menu.main]]
    #   Name = "Case Studies"
    #   parent = "resources"
    #   URL = "/casestudies/"
    #   Post = "Explore how other individuals and companies are transforming business with Monax"
    #   Weight = 2

    # [[menu.main]]
    #   Name = "Tutorials"
    #   parent = "resources"
    #   URL = "/tutorials/"
    #   Post = "Learn how Monax can help you streamline your business using our latest walkthrough tutorials."
    #   Weight = 3

    [[menu.main]]
      Name = "Explainers"
      parent = "resources"
      URL = "/learn/"
      Post = "Learn how Monax can help you streamline your business. Explore best practices and ask questions."
      Weight = 4

    # [[menu.main]]
    #  Name = "Webinars"
    #  parent = "resources"
    #  URL = "/webinars/"
    #  Post = "Join us for industry insight and best practice advice on using legal products to streamline your business."
    #  Weight = 5

    [[menu.main]]
        name = "Company"
        parent = "resources"
        url  = "/company/"
        Post = "Learn about the history of Monax and meet the team behind smart, legally binding contacts on the blockchain."
        weight = 5

[[menu.main]]
    Name = "Pricing"
    indentifier = "pricing"
    URL = "/pricing/"
    Weight = 5

[[menu.register]]
    name = "Book a demo"
    url  = "#"
    weight = 1

# commenting this until we're closer to GA
# [[menu.login]]
#     name = "Login"
#     url  = "https://beta.monax.io/"
#     weight = 7

[params]
    # viewMorePostLink = "/archive/"
    author = "Monax"
    defaultKeywords = ["monax", "agreements network"]
    defaultDescription = "Monax"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "green"

    # Import fonts
    googlefonts = ["Montserrat:300,400,600", "Source Code Pro"]
    fontbody = 'Montserrat'
    fontheadings = 'Montserrat'
    fontcode = 'Source Code Pro'

    # Enable the contact form by entering your Formspree.io email
    email = "contact@monax.io"

    # Format dates with Go's time formatting
    date_format = "2 January, 2006"

    # Main site logo
    logo = "/img/logo.png"

    # Img to display when sharing
    share_img = "/img/share-img.png"

    # Additional scripts - footer
    additional_footer_script_urls = [""]

    # Deprecation notices
    enable_deprecation_warnings = true
    deprecation_warning_text = "Note: since this blog post was written, we have changed our name to Monax Industries and will be changing the name of our product to 'Monax' in early 2017. We have left these posts unedited for the purposes of historical record, as the software was named Eris at the time."

[Permalinks]
    blog = "/blog/:year/:month/:day/:slug/"
    casestudies = "/casestudies/:slug/"
    learn = "/learn/:filename/"
    tutorials = "/tutorials/:slug/"
    webinars = "/webinars/:year/:month/:day/:slug/"
