FROM jguyomard/hugo-builder:0.31-extras

RUN apk add --no-cache --update \
  automake \
  autoconf \
  g++ \
  make \
  zlib-dev \
  nasm \
  nodejs \
  nodejs-npm

RUN npm install -g \
  gulp \
  bower

WORKDIR /site

COPY package.json /site/package.json
COPY .bowerrc /site/.bowerrc
COPY bower.json /site/bower.json

RUN npm install && \
  bower install --allow-root
