#!/usr/bin/env bash
# this file is to be used by jenkins
docker run --name site_deploy --env AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID --env AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY site gulp deploy
docker rm --force site_deploy