#!/usr/bin/env bash
#
# -------------------------------------------------------------
# Usage
# -------------------------------------------------------------
#
# (repo_root)> scripts/deploy [production]
#
# -------------------------------------------------------------
# What It Does
# -------------------------------------------------------------
#
# Deploys the monax site to our gandi servers. The image requires
# that the host have in a key which is within the authorized_keys
# of the production and staging server as it leverages git
# repository on the server side to send the artifacts.
#
# Note this file is to be used by jenkins.
#
# See gulpfile.js for specifics.

docker run --rm -t \
  --volume $HOME/.ssh/:/home/eris/.ssh/ \
  site \
  gulp deploy --$1
