#!/usr/bin/env bash
#
# -------------------------------------------------------------
# Usage
# -------------------------------------------------------------
#
# (repo_root)> scripts/serve
#
# -------------------------------------------------------------
# What It Does
# -------------------------------------------------------------
#
# Builds and serves the monax site for local development. Utilizes
# both gulp watch and hugo serve under the hood in tandem (they)
# operate on separate and isolated directory structures on the
# file system. The mounts the appropriate directories for the
# appropriate binary to watch.
#
# Note this file is to be used for local development.
#
# See gulpfile.js and hugo serve for specifics.

static_dir=`pwd`/static
ip="http://localhost"

setup() {
  # note forcibly assumes the `site` machine on OSX
  if [ "$(uname)" == "Darwin" ]; then
    ip=$(docker-machine ip site)
    if [[ "$ip" == "" ]]; then
      echo "Please make sure you are using your site docker-machine"
      exit 1
    fi
    ip="http://$ip"
  fi

  if [[ `docker images site_buildr -q` == "" ]]
  then
    `pwd`/scripts/build buildr
  elif [[ `docker images site -q` == "" ]]
  then
    `pwd`/scripts/build
  fi

  if [ ! -d "$static_dir" ]; then
    mkdir $static_dir &>/dev/null
  fi

  echo -e "=====================\nserving & waiting\n====================="
}

cleanup() {
  echo "Cleaning"

  docker rm --force site_gulp_watch
  docker rm --force site_hugo_serve

  echo
cat << EOF
  Imma gonna finish up now.

  If you change any of the files outside of the directories:

    * content (used by the hugo watching container)
    * layouts (used by the hugo watching container)
    * source/js (used by the gulp watching container)
    * source/css (used by the gulp watching container)

  then you will need to rebuild the docker image.
  To do so please run [docker rmi site] and then rerun me.

  If you changed anything on the gulp / npm / bower area then
  you will need to rebuild the site_buildr docker image.
  To do so please run [docker rmi site site_buildr] and then
  rerun me. (Note, this takes forever.)

  If you only change things within the above listed directories
  then you can simply rerun me.

  Good-bye!

EOF
}

serve_gulp() {
  docker run --name site_gulp_watch \
    --volume `pwd`/source/js:/site/source/js \
    --volume `pwd`/source/css:/site/source/css \
    --volume `pwd`/source/images:/site/source/images \
    --volume `pwd`/source/data:/site/source/data \
    --volume /site/static \
    site \
    gulp watch-no-build &
}

serve_hugo() {
  docker run --name site_hugo_serve \
    --volume `pwd`/content:/site/content \
    --volume `pwd`/layouts:/site/layouts \
    --volumes-from site_gulp_watch \
    --publish 0.0.0.0:1313:1313 \
    site \
    hugo serve --appendPort --baseURL "$ip" --bind 0.0.0.0 &
}

main() {
  setup
  serve_gulp
  sleep 5
  serve_hugo
  trap "trap - SIGTERM; cleanup $@; kill -- -$$" SIGINT SIGTERM EXIT
  tail -f /dev/null & wait
}

main $@
