#!/usr/bin/env bash

setup() {
  if [[ `docker images site_buildr -q` == "" ]]
  then
    `pwd`/scripts/build buildr
  elif [[ `docker images site -q` == "" ]]
  then
    `pwd`/scripts/build
  fi

  mkdir `pwd`/static &>/dev/null

  echo -e "=====================\nserving & waiting\n====================="
}

cleanup() {
  echo "Cleaning"
  rm -rf `pwd`/static &>/dev/null
  docker rm --force site_gulp_watch
  docker rm --force site_hugo_serve
}

serve() {
docker run --name site_gulp_watch \
  --user eris \
  --volume `pwd`/source:/site/source \
  --volume `pwd`/static:/site/static \
  site \
  gulp watch &

docker run --name site_hugo_serve \
  --user eris \
  --volume `pwd`/content:/site/content \
  --volume `pwd`/layouts:/site/layouts \
  --volume `pwd`/static:/site/static \
  --publish 127.0.0.1:1313:1313 \
  site \
  hugo serve --appendPort --baseURL http://localhost --bind 0.0.0.0 &
}

setup
serve
trap "trap - SIGTERM; cleanup && kill -- -$$" SIGINT SIGTERM EXIT
tail -f /dev/null & wait