#!/usr/bin/env bash
#
# -------------------------------------------------------------
# Usage
# -------------------------------------------------------------
#
# (repo_root)> scripts/test [production]
#
# -------------------------------------------------------------
# What It Does
# -------------------------------------------------------------
#
# Tests the monax site to our gandi servers.
#
# Note this file is to be used for local development or by
# jenkins.
#
# See gulpfile.js for specifics.

if [ "$1" == "production" ]
then
  site=site_test_production
else
  site=site_test_staging
fi

docker run --rm --name $site \
  site \
  gulp test