#!/usr/bin/env bash
#
# -------------------------------------------------------------
# Usage
# -------------------------------------------------------------
#
# (repo_root)> scripts/test
#
# -------------------------------------------------------------
# What It Does
# -------------------------------------------------------------
#
# Tests the monax site to our gandi servers.
#
# Note this file is to be used for local development or by
# jenkins.
#
# See gulpfile.js for specifics.

docker run --rm --name site_test \
  site \
  gulp test